blank_issues_enabled: false
contact_links:
  - name: General Discussion
    url: https://github.com/your-org/nextjs-python-saas-starter/discussions
    about: Ask questions, share ideas, or discuss features with the community

  - name: Documentation
    url: https://github.com/your-org/nextjs-python-saas-starter/blob/main/README.md
    about: Check our comprehensive documentation and setup guides

  - name: System Health
    url: https://backend-production-fd50.up.railway.app/health
    about: Check if the production system is healthy and operational

  - name: API Documentation
    url: https://backend-production-fd50.up.railway.app/docs
    about: Interactive API documentation and testing interface

  - name: Railway Status
    url: https://railway.app/project/ca4e5687-7c67-4a44-aef9-581ec085cc81
    about: Monitor deployment status and system metrics
