name: Security Report
description: Report a security vulnerability (use for responsible disclosure)
title: '[SECURITY] '
labels: ['security', 'critical', 'needs-immediate-attention']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Security Vulnerability Report

        **IMPORTANT: If this is a critical security vulnerability, please report it privately:**

        1. **For critical vulnerabilities:** Email directly instead of creating a public issue
        2. **For security concerns:** Use this form for non-critical security improvements
        3. **For questions:** Use discussions for security best practices

        Thank you for helping keep our multi-tenant SaaS system secure!

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How critical is this security issue?
      options:
        - Critical (RCE, data breach, privilege escalation)
        - High (Authentication bypass, significant data exposure)
        - Medium (Information disclosure, CSRF, XSS)
        - Low (Security hardening, configuration improvements)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Security Category
      description: What type of security issue is this?
      options:
        - Multi-Tenancy & Data Isolation
        - Authentication & Authorization
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - SQL Injection
        - API Security
        - Input Validation
        - Session Management
        - Cryptography & Encryption
        - Dependency Vulnerabilities
        - Infrastructure & Deployment
        - Configuration Security
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Detailed description of the security issue
      placeholder: |
        Provide a clear description of the vulnerability:
        - What is the security flaw?
        - What systems/components are affected?
        - What are the potential consequences?
      render: text
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What could an attacker achieve with this vulnerability?
      placeholder: |
        Describe the potential impact:
        - Data that could be accessed/modified
        - Systems that could be compromised
        - User accounts affected
        - Business operations impact
      render: text
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How to reproduce this vulnerability (if safe to share)
      placeholder: |
        **Only include steps if they don't pose additional risk**

        1. Go to endpoint/page...
        2. Send request with payload...
        3. Observe response...
        4. Security violation occurs...

        **Note:** If reproduction involves sensitive data or could cause harm, 
        describe the general approach without specific details.
      render: text

  - type: textarea
    id: proof_of_concept
    attributes:
      label: Proof of Concept
      description: Evidence of the vulnerability (screenshots, requests/responses)
      placeholder: |
        **Sanitize any sensitive information before sharing**

        Include:
        - Screenshots (with sensitive data redacted)
        - HTTP requests/responses (sanitized)
        - Log entries (without personal data)
        - Code snippets showing the vulnerability
      render: text

  - type: dropdown
    id: environment
    attributes:
      label: Affected Environment
      description: Where was this vulnerability discovered?
      options:
        - Production (Railway)
        - Local Development
        - Testing Environment
        - All Environments
        - Unknown
    validations:
      required: true

  - type: checkboxes
    id: multi_tenancy_impact
    attributes:
      label: Multi-Tenancy Impact
      description: How does this affect our multi-tenant architecture?
      options:
        - label: Could allow access to data from other organizations
          required: false
        - label: Affects organization isolation mechanisms
          required: false
        - label: Could escalate privileges across organizations
          required: false
        - label: Impacts organization-level security controls
          required: false
        - label: Not related to multi-tenancy
          required: false

  - type: textarea
    id: affected_endpoints
    attributes:
      label: Affected Components
      description: Which parts of the system are vulnerable?
      placeholder: |
        **API Endpoints:**
        - /api/endpoint1
        - /api/endpoint2

        **Frontend Pages:**
        - /admin/page1
        - /settings/page2

        **Services:**
        - AuthService
        - OrganizationService
      render: text

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How could this vulnerability be fixed?
      placeholder: |
        Your suggestions for fixing this issue:
        - Immediate workarounds
        - Proper fix implementation
        - Security controls to add
        - Configuration changes needed
      render: text

  - type: textarea
    id: discovery_method
    attributes:
      label: Discovery Method
      description: How was this vulnerability discovered?
      placeholder: |
        - Manual testing
        - Automated security scan
        - Code review
        - Bug bounty research
        - User report
        - Other (please specify)

  - type: input
    id: cve_reference
    attributes:
      label: CVE or Reference
      description: Any related CVE numbers or security advisories?
      placeholder: 'e.g., CVE-2023-12345, GHSA-xxxx-xxxx-xxxx'

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Similar vulnerabilities in the codebase
        - Related security improvements needed
        - Timeline considerations
        - Contact information for follow-up

  - type: checkboxes
    id: responsible_disclosure
    attributes:
      label: Responsible Disclosure
      options:
        - label: I understand this is a public repository and this report will be visible
          required: true
        - label: I have not shared this vulnerability publicly before reporting it here
          required: true
        - label: I have removed/sanitized any sensitive information from this report
          required: true
        - label: I understand the team will respond as quickly as possible
          required: true
        - label: I agree to coordinate with the team on disclosure timeline
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for reporting this security issue responsibly!**

        Our security team will:
        1. Acknowledge your report within 24 hours
        2. Investigate and validate the vulnerability
        3. Develop and test a fix
        4. Deploy the fix to production
        5. Follow up with you on resolution

        **For urgent security issues:** Contact us directly rather than using this public form.
